version: '3'

services:
  lurkmeapp:
    container_name: lurkmeapp
    build: .
    volumes:
      - "./channels.txt:/channels.txt"
    ports:
      - 1234:1234
    restart: always
    env_file:
      - .env
